
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

notify:
  - name: "gmail"
    platform: smtp
    server: "smtp.gmail.com"
    port: 587
    timeout: 15
    sender: "example@gmail.com"
    encryption: starttls
    username: "example@gmail.com"
    password: "password"
    recipient:
      - "example@gmail.com"
    sender_name: "Home Assistant"
